### ISSUE TITLE
Patch release of php-cs-fixer breaks the custom rules of this package.

### ISSUE THREAD

**Issue by LauJosefsen** [erickskrauch/php-cs-fixer-custom-fixers#12]
Hi.

Release 3.59.3 of php-cs-fixer breaks the fixers of this package. Specifically[ this commit](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/commit/064efa1f89bcbc2feb0c6dac90e638329232bea3#diff-e1fb45756cd1d53b6d67072d8a026692c07af55617018229b0bf4ab6c22e3e53), due to the changes of the AbstractFixer no longer implementing the methods `PhpCsFixer\Fixer\ConfigurableFixerInterface::configure` and `PhpCsFixer\Fixer\ConfigurableFixerInterface::getConfigurationDefinition`. 

This is the errors we get:
```
PHP Fatal error:  Class ErickSkrauch\PhpCsFixer\FunctionNotation\AlignMultilineParametersFixer contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (PhpCsFixer\Fixer\ConfigurableFixerInterface::configure, PhpCsFixer\Fixer\ConfigurableFixerInterface::getConfigurationDefinition) in /var/www/html/vendor/erickskrauch/php-cs-fixer-custom-fixers/src/FunctionNotation/AlignMultilineParametersFixer.php on line 36
Fatal error: Class ErickSkrauch\PhpCsFixer\FunctionNotation\AlignMultilineParametersFixer contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (PhpCsFixer\Fixer\ConfigurableFixerInterface::configure, PhpCsFixer\Fixer\ConfigurableFixerInterface::getConfigurationDefinition) in /var/www/html/vendor/erickskrauch/php-cs-fixer-custom-fixers/src/FunctionNotation/AlignMultilineParametersFixer.php on line 36
```

**Comment by erickskrauch** [comment]
Nice of them to break backward compatibility. I'll look into it as soon as I have time.

**Comment by jdreesen** [comment]
Well, the `AbstractFixer` is `@internal`, so there is no BC break here.

**Comment by erickskrauch** [comment]
I meant to say that at the time I originally developed this set of fixers, this class was not `@internal`, but just confirming that it always has been so 😅

**Comment by alamirault** [comment]
I have same issue.

I think dropped methods are replaced by `use PhpCsFixer\Fixer\ConfigurableFixerTrait;`

**Comment by erickskrauch** [comment]
For anyone waiting: I've started work, but as it turns out, there's quite a bit of work to be done to completely abandon `@internal` classes. So it's going to take some time.

**Comment by alamirault** [comment]
Maybe https://github.com/erickskrauch/php-cs-fixer-custom-fixers/pull/14 can be a temporary fix for working in both version and take time for refactoring
