### ISSUE TITLE
ErickSkrauch/align_multiline_parameters not working correctly with union types

### ISSUE THREAD

**Issue by yarikhalupiak** [erickskrauch/php-cs-fixer-custom-fixers#6]
Hi @erickskrauch

The current logic for calculating the length of a type does not consider php8 union types. Could you please let know if you plan to include similar logic?

https://github.com/erickskrauch/php-cs-fixer-custom-fixers/pull/5

**Comment by erickskrauch** [comment]
This fixer also must support both intersections and unions:
* `A|B`
* `A|(B&C)`

**Comment by erickskrauch** [comment]
@yarikhalupiak, released in 1.2.2. Thank you for the issue!
