### ISSUE TITLE
Variadic arguments: extra space is inserted between `...` and variable name

### ISSUE THREAD

**Issue by przepompownia** [erickskrauch/php-cs-fixer-custom-fixers#9]
At first, thanks for publishing this extension.

With 
```php
'ErickSkrauch/align_multiline_parameters' => ['variables' => false, 'defaults' => false],
```
and 
```php
    public function bar(
        string ...$zxc,
    ) {
    } 
```
I get 
```php
    public function bar(
        string ... $zxc,
    ) {
    }
```
as a result, which is not expected.

**Comment by erickskrauch** [comment]
Got it. Will fix it soon.

**Comment by erickskrauch** [comment]
Thank you for this issue. I have fixed it in the commit above. Unfortunately, I will not make a release yet, as I need to test this implementation on my working projects and maybe introduce an option to specify how to align the parameter with variadic.

But you can get the new version now. Use this command:

```sh
composer require --dev erickskrauch/php-cs-fixer-custom-fixers "dev-master#5458830 as 1.2.4"
```

**Comment by przepompownia** [comment]
5458830 works correctly on the example where it failed before for me. Thanks for fixing.
